apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omphalos
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - job.yaml
  - cronjob.yaml
