apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: omphalos-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omphalos-runner
subjects:
  - kind: ServiceAccount
    name: omphalos-runner
roleRef:
  kind: Role
  name: omphalos-runner
  apiGroup: rbac.authorization.k8s.io
