apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: omphalos-runner
  namespace: omphalos
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omphalos-runner
  namespace: omphalos
subjects:
  - kind: ServiceAccount
    name: omphalos-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: omphalos-runner
